[database]
host = "dh726.h.filess.io"
name = "Testing_oxygenlove"
port = 61001
user = "Testing_oxygenlove"
password = "7aa784e9040d7312bd35fcfe577ad9bdf7553593"

[apikey]
ngrok = '2qaPM3tRl12NtJ2mBMRp5QnQItc_6H7Du3N9UkuPCJcWs3UAt'
